### ISSUE TITLE
Replace BlobStorageConfiguration call

### ISSUE THREAD

**Issue by tusmester** [SenseNet/sn-webpages#26]
The `BlobStorageConfiguration` class does not exist anymore in the Services component (v7.3+), replace usages in ascx files with the new API:

```txt
SenseNet.Configuration.BlobStorage
```

For example in this view (line 80):

```txt
/Root/System/SystemPlugins/Portlets/IntraUploadDialog.ascx
```

**Comment by kavics** [comment]
Fixed
